# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# For technical details, see http://travis-ci.org/

language: python
cache: pip
jobs:
  include:
    - stage: test
      python: "3.6"

before_install:
 - "if grep '\t' *.py *.rst; then echo 'Tabs are bad, please use four spaces.'; false; fi"
 - "if grep -n -r '[[:blank:]]$' *.py *.rst; then echo 'Please remove trailing whitespace.'; false; fi"
 - pip install --upgrade pip setuptools
 - pip install flake8 flake8-docstrings restructuredtext-lint black
 - echo "Using restructuredtext-lint to check documentation"
 - restructuredtext-lint *.rst
 - echo "Using flake8 to check Python code"
 - flake8 *.py
 - echo "Using black to check Python code"
 - black --check *.py

install:
 - python setup.py install

script:
 - echo "On this machine \$LANG=$LANG"
 - echo "Checking our own code passes"
 - flake8 --select BLK *.py
 - echo "Checking we report no errors on these test cases"
 - flake8 --select BLK tests/test_cases/*.py
 - flake8 --select BLK --max-line-length 90 tests/test_cases/*.py
 - flake8 --select BLK tests/with_pyproject_toml/*.py
 - flake8 --select BLK --max-line-length 88 tests/with_pyproject_toml/
 - flake8 --select BLK tests/non_conflicting_configurations/*.py
 - echo "Checking we report expected black changes"
 - diff tests/test_changes/hello_world.txt <(flake8 --select BLK tests/test_changes/hello_world.py)
 - diff tests/test_changes/hello_world_EOF.txt <(flake8 --select BLK tests/test_changes/hello_world_EOF.py)
 - diff tests/conflicting_configurations/output.txt <(flake8 --select BLK tests/conflicting_configurations/*.py | sort)

notifications:
  email: false
